### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by jayvenco** [beromir/Servas#39]
First of all, thanks for making this handy app. I use it very often to tag cetrainthings for work/private.
Using my unraid install happily until last app update. Now my original password does not work for some reason. Using sqlite.
Worked fine, no config was  edited prior password issue.

**Comment by beromir** [comment]
This is strange, because no changes were made to the authentication.
Are you just getting the error message that the credentials don't match, or are there other error messages?
Can you try restarting the Docker container?
What version are you using?
Do you see your user account when you run `docker exec -it servas php artisan user:list`?
